name: Keep Render Apps Awake

on:
  schedule:
    - cron: "0 */1 * * *" # every 1 hour
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping portfolio app
        shell: bash
        run: |
          echo "Pinging Trivia Guru..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://trivia-guru.onrender.com/)
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "Success: app is awake! (HTTP $HTTP_STATUS)"
          else
            echo "Failed ping: HTTP $HTTP_STATUS"
            exit 1
          fi
