name: Keep Render Apps Awake

on:
  schedule:
    - cron: "0 */1 * * *" # every 6 hours
  workflow_dispatch:       # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render app
        run: |
          echo "Pinging Trivia Guru..."
          curl -fsSL https://trivia-guru.onrender.com/ || echo "Ping failed, but workflow continues"
